### ISSUE TITLE
Don't warn when the sentence is about a specific person

### ISSUE THREAD

**Issue by sindresorhus** [wooorm/retext-equality#2]
> Ask Peter to review this and ask him what he thinks about it.

This currently warns on `him` and `he`, but I'm writing about a specific person, so gender does matter.

**Comment by wooorm** [comment]
First, this is very hard technical feat: to understand what word refers to what. It cannot be implemented (very fast at least) with certainty. That aside, checking if there’s a capitalised word near these gendered words is not very hard, but I’m not sure if that would work good enough.

Additionally, this might be the first cause for having retext-equality configurable, as I’ve come across reasoning which states that even when referring to a person, and even when their gender is known, using ungendered pronouns is favoured.

For example, even if your doctor (let’s call him peter 😉) is male, referring to him as male might be phrased/read as if most/all doctors are male. I read this somewhere but I don’t known the source anymore.

(and no this is not an answer, and yes it’s vague, it’s a hard problem 😉)

**Comment by sindresorhus** [comment]
> First, this is very hard technical feat: to understand what word refers to what. It cannot be implemented (very fast at least) with certainty.

I thought so too, but I have this feeling you enjoy these kinds of challenges :p

> checking if there’s a capitalised word near these gendered words is not very hard, but I’m not sure if that would work good enough.

Maybe use a list of known human names to help the estimation?

> For example, even if your doctor (let’s call him peter 😉) is male, referring to him as male might be phrased/read as if most/all doctors are male.

Hmm, never heard of that. Are you sure it's just not when writing about doctors in general?

**Comment by wooorm** [comment]
Yes, YES!, and I thought not, I’ll try to find it, at-least I think it had to do with binary thinking (maybe peter identifies as 20% male, 80% female, or something entirely different!)

**Comment by agnoster** [comment]
Configurability could help this by allowing the author to supply something like "gendered_names" or something for people where there's an acceptable gender. I still think this is a good warning for example characters (why not use Sam and Alex and Jerry and use "they" all the time?) but for internal documents where referring to an actual, specific human being it's... weird. In certain circumstances I could actually see using "they" rather than the person's pronoun could be kind of disrespectful - if you have to fight every day to be gendered correctly, it would probably suck for the automatic text checker to deny you your pronoun.

In general it would be nice to be able to extend this in various ways, both providing "allowed_terms" (we use "pop", but never with the meaning of "male parent"), additional patterns ("transgendered" -> "transgender, trans, trans*"), and potentially "gendered_names" ("John": "male" or just a list).

**Comment by wooorm** [comment]
No idea yet on how to fix this. So I’m closing this for now! But I’ll keep it in mind :)
