### ISSUE TITLE
More ableist terms

### ISSUE THREAD

**Issue by wooorm** [wooorm/retext-equality#6]
http://www.autistichoya.com/p/ableist-words-and-terms-to-avoid.html

**Comment by alexgleason** [comment]
Nice, I was just about to add dumb when I saw you did it. Though I want to note something about the word "stupid" here: https://github.com/wooorm/retext-equality/blob/8d835e22e2e47d4f0a51159818492d64fdb667a2/script/ablist.yml#L399

That word may arguable not be a good replacement. It depends on the context. The thing about stupid is that you're suggesting something is bad because it lacks intelligence.

* When used towards a person, you are entirely devaluing them based on one quality. As a programmer this was difficult for me to grasp at first because I do value intelligence above all else, but this word can be offensive especially towards people who do have low intelligence. As Einstein said: “Everybody is a genius. But if you judge a fish by its ability to climb a tree, it will live its whole life believing that it is stupid.”
* When used towards a computer, for example, whose only purpose in life is to be "smart", this word adequately describes the deficiency the device has.

But since that word can be used in an offensive manner it may be better to err on the side of caution. I'm open to discussion about it.

**Comment by wooorm** [comment]
Thanks @alexgleason for the feedback; I indeed though a little (but not too much) when I added it. I added because I has your PR in mind, “This is dumb!”, and thought it could fittingly be changed to “This is stupid!”

Are there other alternatives you can think of for “dumb”, in that context?

**Comment by alexgleason** [comment]
Perhaps "dislikable" could be a replacement. Because when most people are saying "x is dumb" the sentiment is just "I dislike this".

**Comment by alexgleason** [comment]
This also raises the question of whether stupid should be added as an abelist term. The author of the linked article would believe so and I'd be interested to hear their opinion. But in the interim it might be best to just remove "stupid" as a suggested alternative and leave it at that.

Basically my thought is, don't enforce it (until there it a convincing reason to do so) but don't encourage it either.

**Comment by wooorm** [comment]
How about `foolish`, `ludicrous`?

**Comment by alexgleason** [comment]
Nice! :+1: I'm impressed with your ability to come up with words.

**Comment by wooorm** [comment]
thesaurus.com haha :wink:

**Comment by alexgleason** [comment]
I sent the author of that website an email asking for further clarification on the word "stupid". Will post back if I get a response.

**Comment by wooorm** [comment]
:+1:

**Comment by alexgleason** [comment]
Okay, so I got a response, with a mind-blowing linked article. [Deconstructing "Stupid"](http://www.mmonjejr.com/2014/02/deconstructing-stupid.html)

After reading this, I think the word should be added, mainly because disabled people consider it to be a slur. The main thing that made it click for me was this line from the article:

>I think it's fairly easy to see how these definitions can bleed into our common idiom through the natural human predisposition toward personifying tools and possessions. The stupid PS3 controller is the one that didn't do what we expected when we hit the buttons.

The word was created to describe humans (it's derived from "in a stupor"), and we are personifying objects when we use that word towards objects. And the fact that "stupid" has a negative connotation and describes a lack of human perception is insensitive and wrong. Again, Einstein put it best:

>“Everybody is a genius. But if you judge a fish by its ability to climb a tree, it will live its whole life believing that it is stupid.”

The value that people bring to the world can't be measured by their perceptive abilities alone (perceptive abilities is often what we refer to as intelligence, though there are many forms of it). The word "stupid" suggests that a person is wholly bad due to a lack of one quality.

A replacement word may be something like "bad", or a more specific word that has an inanimate connotation like "inoperable".

I'm tempted to even include synonyms like "idiot" and even "unintelligent".
